version: "3.1"

services:
  influxdb:
    image: influxdb:latest
    container_name: micromes-influxdb
    ports:
      - ${INFLUX_PORT:-8086}:8086
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUX_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PSW}
    networks:
      - micromes-network-influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:

networks:
  micromes-network-influxdb:
    name: micromes-network-influxdb
