version: "3.8"

services:
  emqx:
    image: emqx/emqx:latest
    container_name: micromes-emqx-broker
    restart: on-failure
    environment:
      - EMQX_DASHBOARD__DEFAULT_USER__USERNAME=${EMQX_USER}
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=${EMQX_PASSWORD}
    ports:
      - ${EMQX_PORT__UI:-18083}:18083
      - ${EMQX_PORT__MQTT:-1883}:1883
      - ${EMQX_PORT__WS:-8083}:8083
      - ${EMQX_PORT__WSS:-8084}:8084
      - ${EMQX_PORT__MQTT_TLS:-8883}:8883
    networks:
      - micromes-network-broker
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
      - emqx_etc:/opt/emqx/etc

volumes:
  emqx_data:
  emqx_log:
  emqx_etc:

networks:
  micromes-network-broker:
    name: micromes-network-broker
